#!/bin/bash
# Get a comprehensive map of the symmetry spacegroups of all structures in a concatenated CIF file.
# This script assumes that the line header '_symmetry_Int_Tables_number', automatically generated by
# Pymatgen's CifWriter, is used to define the spacegroup number of all structures.
# This script's main goal is to show the symmetrization results from metrics_pipeline/preprocess.py.

GetSpgCount10 () {
	spg0=$1
	spg1=$(($spg0 + 1))
	spg2=$(($spg1 + 1))
	spg3=$(($spg2 + 1))
	spg4=$(($spg3 + 1))
	spg5=$(($spg4 + 1))
	spg6=$(($spg5 + 1))
	spg7=$(($spg6 + 1))
	spg8=$(($spg7 + 1))
	spg9=$(($spg8 + 1))
	count0=$(grep -c "^_symmetry_Int_Tables_number   $spg0$" "$2")
	count1=$(grep -c "^_symmetry_Int_Tables_number   $spg1$" "$2")
	count2=$(grep -c "^_symmetry_Int_Tables_number   $spg2$" "$2")
	count3=$(grep -c "^_symmetry_Int_Tables_number   $spg3$" "$2")
	count4=$(grep -c "^_symmetry_Int_Tables_number   $spg4$" "$2")
	count5=$(grep -c "^_symmetry_Int_Tables_number   $spg5$" "$2")
	count6=$(grep -c "^_symmetry_Int_Tables_number   $spg6$" "$2")
	count7=$(grep -c "^_symmetry_Int_Tables_number   $spg7$" "$2")
	count8=$(grep -c "^_symmetry_Int_Tables_number   $spg8$" "$2")
	count9=$(grep -c "^_symmetry_Int_Tables_number   $spg9$" "$2")

	# Formatting outputs
	printf -v fspg0 "%03d" $spg0
	printf -v fspg1 "%03d" $spg1
	printf -v fspg2 "%03d" $spg2
	printf -v fspg3 "%03d" $spg3
	printf -v fspg4 "%03d" $spg4
	printf -v fspg5 "%03d" $spg5
	printf -v fspg6 "%03d" $spg6
	printf -v fspg7 "%03d" $spg7
	printf -v fspg8 "%03d" $spg8
	printf -v fspg9 "%03d" $spg9
	printf -v fcount0 "%0$3d" $count0
	printf -v fcount1 "%0$3d" $count1
	printf -v fcount2 "%0$3d" $count2
	printf -v fcount3 "%0$3d" $count3
	printf -v fcount4 "%0$3d" $count4
	printf -v fcount5 "%0$3d" $count5
	printf -v fcount6 "%0$3d" $count6
	printf -v fcount7 "%0$3d" $count7
	printf -v fcount8 "%0$3d" $count8
	printf -v fcount9 "%0$3d" $count9
}

CountCrystalSystem () {
	if [ $1 -le 2 ]; then
		triclinic=$(($triclinic + $2))
	elif [ $1 -le 15 ]; then
		monoclinic=$(($monoclinic + $2))
	elif [ $1 -le 74 ]; then
		orthorombic=$(($orthorombic + $2))
	elif [ $1 -le 142 ]; then
		quadratic=$(($quadratic + $2))
	elif [ $1 -le 167 ]; then
		trigonal=$(($trigonal + $2))
	elif [ $1 -le 194 ]; then
		hexagonal=$(($hexagonal + $2))
	else
		cubic=$(($cubic + $2))
	fi
}

FormatCrystalSystemCounts () {
	printf -v tric "%0$1d" $2
	printf -v mono "%0$1d" $3
	printf -v orth "%0$1d" $4
	printf -v quad "%0$1d" $5
	printf -v trig "%0$1d" $6
	printf -v hexa "%0$1d" $7
	printf -v cubi "%0$1d" $8
}

StoreCrystalSystemCounts () {
	total_triclinic=$(($total_triclinic + $triclinic))
	total_monoclinic=$(($total_monoclinic + $monoclinic))
	total_orthorombic=$(($total_orthorombic + $orthorombic))
	total_quadratic=$(($total_quadratic + $quadratic))
	total_trigonal=$(($total_trigonal + $trigonal))
	total_hexagonal=$(($total_hexagonal + $hexagonal))
	total_cubic=$(($total_cubic + $cubic))
}

debug=0
compute_sum=0
total_triclinic=0
total_monoclinic=0
total_orthorombic=0
total_quadratic=0
total_trigonal=0
total_hexagonal=0
total_cubic=0

for file in "$@"; do
	if [ $file == "--debug" ]; then
		debug=1
		continue
	elif [ $file == "--sum" ]; then
		compute_sum=1
		continue
	fi

	echo ""
	echo "Analysing symmetries in $file:"
	triclinic=0
	monoclinic=0
	orthorombic=0
	quadratic=0
	trigonal=0
	hexagonal=0
	cubic=0
	structs_num=$(grep -c "^data_" "$file")
	spg_num=$(grep -c "^_symmetry_Int_Tables_number" "$file")
	max_digit=${#spg_num}
	echo ""
	echo "Spacegroups details:"
	spgsum=0
	for spg in {1..221..10}; do
		GetSpgCount10 $spg "$file" $max_digit
		echo "$fspg0: $fcount0 | $fspg1: $fcount1 | $fspg2: $fcount2 | $fspg3: $fcount3 | $fspg4: $fcount4 | $fspg5: $fcount5 | $fspg6: $fcount6 | $fspg7: $fcount7 | $fspg8: $fcount8 | $fspg9: $fcount9"
		spgsum=$(($spgsum + $count0 + $count1 + $count2 + $count3 + $count4 + $count5 + $count6 + $count7 + $count8 + $count9))
		CountCrystalSystem $spg0 $count0
		CountCrystalSystem $spg1 $count1
		CountCrystalSystem $spg2 $count2
		CountCrystalSystem $spg3 $count3
		CountCrystalSystem $spg4 $count4
		CountCrystalSystem $spg5 $count5
		CountCrystalSystem $spg6 $count6
		CountCrystalSystem $spg7 $count7
		CountCrystalSystem $spg8 $count8
		CountCrystalSystem $spg9 $count9
	done
	StoreCrystalSystemCounts
	file_cs_sum=$(($triclinic + $monoclinic + $orthorombic + $quadratic + $trigonal + $hexagonal + $cubic))
	FormatCrystalSystemCounts $max_digit $triclinic $monoclinic $orthorombic $quadratic $trigonal $hexagonal $cubic
	echo ""
	echo "Crystal Systems details:"
	echo "Triclinic: $tric | Monoclinic: $mono | Orthorombic: $orth | Quadratic: $quad"
	echo "Trigonal:  $trig | Hexagonal:  $hexa | Cubic:       $cubi | Sum (Scs): $file_cs_sum"
	echo ""
	echo "Number of structures (Nst): $structs_num"
	echo "Number of spacegroups (Nsg): $spg_num"
	echo "Sum of listed spacegroups (Ssg): $spgsum"
	echo ""
done

if [ $compute_sum -eq 1 ]; then
	total_sum=$(($total_triclinic + $total_monoclinic + $total_orthorombic + $total_quadratic + $total_trigonal + $total_hexagonal + $total_cubic))
	total_max_digit=${#total_sum}
	FormatCrystalSystemCounts $total_max_digit $total_triclinic $total_monoclinic $total_orthorombic $total_quadratic $total_trigonal $total_hexagonal $total_cubic
	echo ""
	echo "Total sum of Crystal system distributions from all evaluated files:"
	echo "Triclinic: $tric | Monoclinic: $mono | Orthorombic: $orth | Quadratic: $quad"
	echo "Trigonal:  $trig | Hexagonal:  $hexa | Cubic:       $cubi | Total Sum: $total_sum"
	echo ""
fi

if [ $debug -eq 1 ]; then
	echo ""
	echo "|----------------------------------------------------------------------------------------|"
	echo "| Debug Notes:                                                                           |"
	echo "| For each file analysis:                                                                |"
	echo "| - (Scs == Nst == Nsg == Ssg != 0) => Everything is fine, result is reliable.           |"
	echo "| - Scs < Nsg => The CountCrystalSystem function skipped some counting.                  |"
	echo "| - Nst == 0 => Verify that the file respects CIF formatting.                            |"
	echo "| - Nst > Nsg => Some data do not contain the '_symmetry_Int_Tables_number' line header. |"
	echo "| - Nst == Nsg != Ssg => An edge case in file is probably causing a bug in the script.   |"
	echo "|----------------------------------------------------------------------------------------|"
	echo ""
fi
