#!/bin/bash
# Get a comprehensive map of the symmetry spacegroups of all structures in a concatenated CIF file.
# This script assumes that the line header '_symmetry_Int_Tables_number', automatically generated by
# Pymatgen's CifWriter, is used to define the spacegroup number of all structures.
# This script's main goal is to show the symmetrization results from metrics_pipeline/preprocess.py.

GetSpgCount10 () {
	local spg0=$1
	local spg1=$(($spg0 + 1))
	local spg2=$(($spg1 + 1))
	local spg3=$(($spg2 + 1))
	local spg4=$(($spg3 + 1))
	local spg5=$(($spg4 + 1))
	local spg6=$(($spg5 + 1))
	local spg7=$(($spg6 + 1))
	local spg8=$(($spg7 + 1))
	local spg9=$(($spg8 + 1))
	count0=$(grep -c "^_symmetry_Int_Tables_number   $spg0$" "$2")
	count1=$(grep -c "^_symmetry_Int_Tables_number   $spg1$" "$2")
	count2=$(grep -c "^_symmetry_Int_Tables_number   $spg2$" "$2")
	count3=$(grep -c "^_symmetry_Int_Tables_number   $spg3$" "$2")
	count4=$(grep -c "^_symmetry_Int_Tables_number   $spg4$" "$2")
	count5=$(grep -c "^_symmetry_Int_Tables_number   $spg5$" "$2")
	count6=$(grep -c "^_symmetry_Int_Tables_number   $spg6$" "$2")
	count7=$(grep -c "^_symmetry_Int_Tables_number   $spg7$" "$2")
	count8=$(grep -c "^_symmetry_Int_Tables_number   $spg8$" "$2")
	count9=$(grep -c "^_symmetry_Int_Tables_number   $spg9$" "$2")
	printf -v fspg0 "%03d" $spg0
	printf -v fspg1 "%03d" $spg1
	printf -v fspg2 "%03d" $spg2
	printf -v fspg3 "%03d" $spg3
	printf -v fspg4 "%03d" $spg4
	printf -v fspg5 "%03d" $spg5
	printf -v fspg6 "%03d" $spg6
	printf -v fspg7 "%03d" $spg7
	printf -v fspg8 "%03d" $spg8
	printf -v fspg9 "%03d" $spg9
	printf -v fcount0 "%0$3d" $count0
	printf -v fcount1 "%0$3d" $count1
	printf -v fcount2 "%0$3d" $count2
	printf -v fcount3 "%0$3d" $count3
	printf -v fcount4 "%0$3d" $count4
	printf -v fcount5 "%0$3d" $count5
	printf -v fcount6 "%0$3d" $count6
	printf -v fcount7 "%0$3d" $count7
	printf -v fcount8 "%0$3d" $count8
	printf -v fcount9 "%0$3d" $count9
}

for file in "$@"; do
	echo "Analysing symmetries in $file:"
	structs_num=$(grep -c "^data_" "$file")
	spg_num=$(grep -c "^_symmetry_Int_Tables_number" "$file")
	max_digit=${#spg_num}
	echo "Spacegroups details:"
	spgsum=0
	for spg in {1..221..10}; do
		GetSpgCount10 $spg "$file" $max_digit
		echo "$fspg0: $fcount0, $fspg1: $fcount1, $fspg2: $fcount2, $fspg3: $fcount3, $fspg4: $fcount4, $fspg5: $fcount5, $fspg6: $fcount6, $fspg7: $fcount7, $fspg8: $fcount8, $fspg9: $fcount9"
		spgsum=$(($spgsum + $count0 + $count1 + $count2 + $count3 + $count4 + $count5 + $count6 + $count7 + $count8 + $count9))
	done
	echo "Total number of structures (Tst): $structs_num"
	echo "Total number of spacegroups (Tsg): $spg_num"
	echo "Sum of listed spacegroups (Ssg): $spgsum"
done

echo "|----------------------------------------------------------------------------------------|"
echo "| Debug Notes:                                                                           |"
echo "| For each file analysis:                                                                |"
echo "| - (Tst == Tsg == Ssg != 0) => Everything is fine, result is reliable.                  |"
echo "| - Tst == 0 => Verify that the file respects CIF formatting.                            |"
echo "| - Tst > Tsg => Some data do not contain the '_symmetry_Int_Tables_number' line header. |"
echo "| - Tst == Tsg != Ssg => An edge case in file is probably causing a bug in the script.   |"
echo "|----------------------------------------------------------------------------------------|"