#!/bin/bash

export REJECT=$HOME/Batch_test/Relaxations/0_TiO2/rejected.txt
export BANDGAP=$HOME/Batch_test/Band_gaps_full_bg
export BGPLUS=$BANDGAP/0_TiO2_best_plus
export BGZERO=$BANDGAP/0_TiO2_best_neutral
export BGMINUS=$BANDGAP/0_TiO2_best_minus

if [ -f $REJECT ]; then
rm $REJECT
fi

if [ -d $BGPLUS ]; then
rm -r $BGPLUS
fi

if [ -d $BGZERO ]; then
rm -r $BGZERO
fi

if [ -d $BGMINUS ]; then
rm -r $BGMINUS
fi

