[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "metrics-pipeline"
version = "4.0.2"
description = "Screening pipeline for metrics evaluation in Generative AI for materials"
readme = "README.md"
license-files = ["LICENSE"]
authors = [
  { name = "Elohan Veillon", email = "elohan.veillon@gmail.com" },
  { name = "Astrid Klipfel", email = "astrid.klipfel@univ-artois.fr" }
]
requires-python = ">=3.10,<4.0"
dynamic = [ "dependencies" ]

[project.scripts]
# Main pipeline scripts
preprocess = "metrics_pipeline.preprocess:main"
concatenate = "metrics_pipeline.concatenate:main"
dataset_loader = "metrics_pipeline.dataset_loader:main"
vasp_rundir_writer = "metrics_pipeline.vasp_rundir_writer:main"
phase_diag_energies = "metrics_pipeline.phase_diag_energies:main"
summarize_relaxations = "metrics_pipeline.summarize_relaxations:main"
metrics = "metrics_pipeline.metrics:main"

# Optional scripts
alignn_pd_dataset = "metrics_pipeline.opt_scripts.alignn_pd_dataset:main"
cif_counter = "metrics_pipeline.opt_scripts.cif_counter:main"
cif_to_poscar = "metrics_pipeline.opt_scripts.cif_to_poscar:main"
create_summary = "metrics_pipeline.opt_scripts.create_summary:main"
dsol_bandgap = "metrics_pipeline.opt_scripts.dsol_bandgap:main"
generate_slurm = "metrics_pipeline.opt_scripts.generate_slurm:main"
parse_csv = "metrics_pipeline.opt_scripts.parse_csv:main"
plot_sym_dists = "metrics_pipeline.opt_scripts.plot_sym_dists:main"
summary_paths_update = "metrics_pipeline.opt_scripts.summary_paths_update:main"
symmetry_mapping = "metrics_pipeline.opt_scripts.symmetry_mapping:main"
symmetry_parser = "metrics_pipeline.opt_scripts.symmetry_parser:main"

[tool.poetry]
packages = [
  { include = "metrics_pipeline", from = "src" },
  { include = "structure_perturbator", from = "src" }
]
include = ["bash_scripts"]

[tool.poetry.dependencies]
python = "^3.10"
pymatgen = ">=2023.10.11"
spglib = ">=2.0.0"
torch = "~2.3.0"
torch-cluster = {version = "^1.6.3+pt23cpu", source = "pytorch-geometric"}
torch-scatter = {version = "^2.1.2+pt23cpu", source = "pytorch-geometric"}
torch-geometric = "^2.3.0"
materials-toolkit = { git = "https://github.com/materials-toolkits/pymaterials.git", branch = "pre-release", rev="c777b3a" }
matminer = "^0.9.2"
mp-api = "^0.41.2"

[tool.poetry.group.dev.dependencies]
pytest = ">=9.1.0"
pylint = ">=4.0.0"

[[tool.poetry.source]]
name = "pytorch-geometric"
url = "https://data.pyg.org/whl/torch-2.3.0+cpu.html"
priority = "explicit"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

