# Configuration of VASP input files for Δ-Sol computations with PBE 5.4 PAW pseudopotentials.
# Reference of the Δ-Sol method: M.K.Y. Chan and G. Ceder, Phys. Rev. Lett., 105, 196403 (2010).
#
# DFT+U corrections are the ones proposed in 2011 by Jain et al.:
# A. Jain, G. Hautier, C.J. Moore, S.P. Ong, C.C. Fischer, T. Mueller, K.A. Persson, and G. Ceder, 
# Computational Materials Science, 50, 2295-2310 (2011).
#
# The choices for the pseudopotentials to use are from Pymatgen's "PBE54Base.yaml" file.
# Pymatgen official documentation: https://pymatgen.org/
# Pymatgen's reference:
# Shyue Ping Ong, William Davidson Richards, Anubhav Jain, Geoffroy Hautier,
# Michael Kocher, Shreyas Cholia, Dan Gunter, Vincent Chevrier, Kristin A.
# Persson, Gerbrand Ceder. *Python Materials Genomics (pymatgen) : A Robust,
# Open-Source Python Library for Materials Analysis.* Computational Materials
# Science, 2013, 68, 314–319. https://doi.org/10.1016/j.commatsci.2012.10.028


INCAR:
  ALGO: Normal
  EDIFF: 0.00001
  ENCUT: 520
  ISMEAR: -5
  NELM: 200
  NSW: 0
  PREC: Accurate
  LDAU: true
  LDAUTYPE: 2
  LDAUPRINT: 1
  LDAUJ:
    F:
      Co: 0
      Cr: 0
      Fe: 0
      Mn: 0
      Mo: 0
      Ni: 0
      V: 0
      W: 0
    O:
      Co: 0
      Cr: 0
      Fe: 0
      Mn: 0
      Mo: 0
      Ni: 0
      V: 0
      W: 0
  LDAUL:
    F:
      Co: 2
      Cr: 2
      Fe: 2
      Mn: 2
      Mo: 2
      Ni: 2
      V: 2
      W: 2
    O:
      Co: 2
      Cr: 2
      Fe: 2
      Mn: 2
      Mo: 2
      Ni: 2
      V: 2
      W: 2
  LDAUU:
    F:
      Co: 3.32
      Cr: 3.7
      Fe: 5.3
      Mn: 3.9
      Mo: 3.5
      Ni: 6.2
      V: 3.25
      W: 6.2
    O:
      Co: 3.32
      Cr: 3.7
      Fe: 5.3
      Mn: 3.9
      Mo: 3.5
      Ni: 6.2
      V: 3.25
      W: 6.2

KPOINTS:
  reciprocal_density: 10000

POTCAR_FUNCTIONAL: PBE_54_W_HASH
POTCAR:
  Ac: Ac
  Ag: Ag
  Al: Al
  Am: Am
  Ar: Ar
  As: As
  At: At
  Au: Au
  B: B
  Ba: Ba_sv
  Be: Be_sv
  Bi: Bi
  Br: Br
  C: C
  Ca: Ca_sv
  Cd: Cd
  Ce: Ce
  Cf: Cf
  Cl: Cl
  Cm: Cm
  Co: Co
  Cr: Cr_pv
  Cs: Cs_sv
  Cu: Cu_pv
  Dy: Dy_3
  Er: Er_3
  Eu: Eu
  F: F
  Fe: Fe_pv
  Fr: Fr_sv
  Ga: Ga_d
  Gd: Gd
  Ge: Ge_d
  H: H
  He: He
  Hf: Hf_pv
  Hg: Hg
  Ho: Ho_3
  I: I
  In: In_d
  Ir: Ir
  K: K_sv
  Kr: Kr
  La: La
  Li: Li_sv
  Lu: Lu_3
  Mg: Mg_pv
  Mn: Mn_pv
  Mo: Mo_pv
  N: N
  Na: Na_pv
  Nb: Nb_pv
  Nd: Nd_3
  Ne: Ne
  Ni: Ni_pv
  Np: Np
  O: O
  Os: Os_pv
  P: P
  Pa: Pa
  Pb: Pb_d
  Pd: Pd
  Pm: Pm_3
  Po: Po_d
  Pr: Pr_3
  Pt: Pt
  Pu: Pu
  Ra: Ra_sv
  Rb: Rb_sv
  Re: Re_pv
  Rh: Rh_pv
  Rn: Rn
  Ru: Ru_pv
  S: S
  Sb: Sb
  Sc: Sc_sv
  Se: Se
  Si: Si
  Sm: Sm_3
  Sn: Sn_d
  Sr: Sr_sv
  Ta: Ta_pv
  Tb: Tb_3
  Tc: Tc_pv
  Te: Te
  Th: Th
  Ti: Ti_pv
  Tl: Tl_d
  Tm: Tm_3
  U: U
  V: V_pv
  W: W_sv
  Xe: Xe
  Y: Y_sv
  Yb: Yb_3
  Zn: Zn
  Zr: Zr_sv
